# This is an appspec.yml template file for use with AWS CodeDeploy.
# Specify "os: linux" or "os: windows".
os:  
# You can specify one or more mappings in the files section. Remove this
    section if you are not using it.
files:
  - source: 
    destination:
# For deployments to instances other than Windows Server, you can
#   use a "permissions" section to describe special permissions to apply 
#   to your files as they are being copied to the instance. Remove this
#   section if you are not using it.
permissions:
  - object:
    pattern:
    except:
    owner:
    group:
    mode: 
    acls:
      -
    context:
      user:
      type:
      range:
    type:
      -
# The lifecycle hooks sections allows you to specify deployment scripts.
# If you are not running any commands on the instance, remove this 
#   section.
hooks:
  ApplicationStop:
    - location: 
      timeout:
      runas:
    - location: 
      timeout:
      runas: 
# During the BeforeInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  BeforeInstall:
    - location: 
      timeout:
      runas: 
    - location: 
      timeout:
      runas:
# During the AfterInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  AfterInstall:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas:
# During the ApplicationInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ApplicationStart:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas:
# During the ValidateService deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ValidateService:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas: